apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

  labels:
    app: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend-container
          image: gowdaamith/frontend:v1

          ports:
            - containerPort: 3000

          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: BACKEND_URL

          resources: 
            limits: 
              cpu: "0.5"
              memory: "100Mi"
            requests: 
              cpu: "0.5"
              memory:  "50Mi"



