name: frontend-deployment
app: frontend
replicaCount: 1
containerName: frontend-container
image: 
  repository: gowdaamith/frontend
  tag: v3
ports:
  containerrPort: 3000
configMap:
  name: app-configMap
  APP_NAME: HE-HOO
  ENVIRONMENT: PROD
  FEATURE_FLAG: "true"
  BACKEND_URL: http://backend-service:3000
  DB_HOST: mongo-service

resource:
  requests:
    cpu: 
    memory:
  limits:
    cpu:
    memory:
startupProbe:
  path: /
  port: 3000
  failureThreshold: 30
  periodSeconds: 5
livenessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
readinessProbe:
  path: /
  port: 3000
  periodSeconds: 5

servicename: frontend-service
protocol: TCP
serviceport: 80
containerPort: 3000
typeport: NodePort



