apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongo-service
  replicas: 1

  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      labels:
        app: mongo

    spec:
      containers:
        - name: mongodb
          image: mongo:6

          ports:
            - containerPort: 27017
          
          startupProbe: 
            tcpSocket:
              port:  27017
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe: 
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket: 
               port: 27017
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASS
          
          resources: 
            requests: 
              cpu: "250m"
              memory: "512Mi"
            limits: 
              cpu: "500m"
              memory: "600Mi"


          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db


  volumeClaimTemplates:
    - metadata:
        name: mongo-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi
