apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: backend
  template: 
    metadata:
      labels: 
        app: backend
    spec:
      containers:
      - name: backend
        image: gowdaamith/backend:v2
        ports: 
        - containerPort: 80
       
        env: 
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: APP_NAME
          - name: ENVIRONMENT
            valueFrom: 
              configMapKeyRef:
                name: app-configmap
                key: ENVIRONMENT

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASS

          - name: DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: app-configmap
                key: DB_HOST
        resources: 
          requests: 
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: " 512Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet: 
            path: /health
            port: 3000
          periodSeconds: 5

                    
