piVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.deployement.name}}
  labels:
    app: {{ .Values.deployment.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.containername }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
          - name: APP_NAME
            valueFrom:
             configMapKeyRef:
               name: {{ .Values.configMap.configMapfilename }}
               key: {{ .Values.configMap.APP_NAME}}
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configMap.configMapfilename }}
                key: {{ .Values.configMap.ENVIRONMENT }}
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configMap.configMapfilename }}
                key: {{ .Values.configMap.DB_HOST }}
          - name: DB_ADMIN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.secretfilename }}
                key: {{ .Values.secret.DB_ADMIN }}
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.secretfilename }}
                key: {{ .Values.secret.DB_PASS }}
           resource:
             requests:
               cpu: {{ .Values.requests.cpu }}
               memory: {{ .Values.requests.memory }}
             limits:
               cpu: {{ .Values.limits.cpu }}
               memory: {{ .Values.limits.memory }}
           startupProbe:
             httpGet:
               path: {{ .Values.startupProbe.path }}
               port: {{ .Values.startupProbe.port }}
             failureThreshold: {{ .Values.startupProbe.failureThreshold }}
             periodSeconds: {{ .Values.startupProbe.periodSeconds }}
           livnessProbe:
             httpGet:
               path: {{ .Values.livenssProbe.path }}
               port: {{ .Values.livenssProbe.port }}
             initialDeloySeconds: {{ .Values.livenessProbe.initialDelaySecond}}
             periodSeconds: {{ .Values.livenessProbe.periodSecond }}

           readinessProbe:
             httpGet:
               path: {{ .Values.readinessProbe.path }}
               port: {{ .Values.readinessProbe.port }}
             periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
