apiVersion: 
kind: Service
metadata: 
  name:  {{ .Values.service.name }}
spec: 
  selector: 
    app: {{ .Values.sevice.app }}
  ports: 
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targerPort }}
  type:  {{ .Values.service.type }}
